name: Android CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Slack Notifications
      uses: slackapi/slack-github-action@v1.23.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#android-experiments'
      if: always()
